### PR TITLE
Move to golang 1.11

### PR DESCRIPTION
**Pull request by lox**

### CODE REVIEW

**Comment by itsdalmo** [comment]
Loving it! I have not used go mods myself yet, but is _not_ using a vendor folder the recommended practice now? In the past the rule of thumb I've heard has been that libraries should not use a vendor folder, while binaries should vendor?

**Comment by lox** [comment]
@itsdalmo yeah, the go team basically recommends not vendoring with modules. When modules are active `vendor/` is ignored.

**Comment by toolmantim** [comment]
image

😱

**Comment by lox** [comment]
Closing in favour of #59.

**Pull request closed without merging**
