### PR TITLE
Fix dangling queues on startup

### PR DESCRIPTION
**Pull request by itsdalmo**
Note: This branch is made on top of https://github.com/buildkite/lifecycled/pull/26 because the changes are interlinked.

### CODE REVIEW

**Comment by lox** [comment]
Mind rebasing on top of the latest master?

**Comment by lox** [comment]
There is a lot going on in this PR! 😓Any way we can split this up a bit?

**Comment by itsdalmo** [comment]
Yeah, I can try to split out the context changes into a separate PR! Not a git wizard but I'll do my best ;D

**Comment by itsdalmo** [comment]
Ok, hopefully this is easier to review. The gist of it:
- Remove session from `Queue`; primarily because it enables us to create mock clients and write unit tests for queue (in the future).
- Split `CreateQueue` and `Delete` so that we can have separate deferred calls so that the queue is deleted if we e.g. fail to subscribe to the topic (described here: https://github.com/buildkite/lifecycled/issues/25). Likewise, we want to delete the queue even if we fail to delete the SNS subscription.

The goal (which has now been removed from the PR) is to add `context.Context` so that we can unwind the call stack and _just_ use deferred calls in `main.go` (or `daemon.go`) to clean everything up (also lets us remove the two `sync.Once`).

If you want these changes; let me know if you need me to squash the commits first, or if you'd rather like to use the "squash and merge" button.

**Comment by itsdalmo** [comment]
Ah, just saw that I had actually had the foresight to split the PR's into smaller pieces:
https://github.com/buildkite/lifecycled/pull/26

So, my initial thought was that if you approved and merged #26 I could update _this_ PR and it would be easier to review. But they are tightly coupled so one does not really make a lot of sense without the other 🤔

**Comment by lox** [comment]
Ok, #26 is merged. Mind rebasing this and we'll re-evaluate?

**Comment by lox** [comment]
Closing in favor of #30.

**Pull request closed without merging**
